/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class InternalSpeakersJNI */
#include <android/log.h>

#define LOG_TAG "INTERNALSPEAKERS"
#define LOGV(...) __android_log_print(ANDROID_LOG_SILENT, LOG_TAG, __VA_ARGS__)
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)

#ifndef _Included_InternalSpeakersJNI
#define _Included_InternalSpeakersJNI
#ifdef __cplusplus


extern "C" {
#endif
/*
 * Class:     InternalSpeakersJNI
 * Method:    toggleInternalSpeakers
 * Signature: (Z)V
 */
JNIEXPORT void Java_com_android_settings_notification_InternalSpeakersJNI_toggleInternalSpeakers 
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     InternalSpeakersJNI
 * Method:    returnFirmwareVersion
 * Signature: (Z)V
 */
JNIEXPORT jstring JNICALL Java_com_android_settings_notification_InternalSpeakersJNI_returnFirmwareVersion 
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
